import { useMemo, useState, useEffect } from "react";
import { Copy, Mail, FileText, Settings, Printer } from "lucide-react";
import { useToast } from "../context/ToastContext";
import MarkdownText from "../components/MarkdownText";

export default function Share() {
  const { pushToast } = useToast();

  // Load last generated content from local storage
  const [summary, setSummary] = useState("");
  const [chunks, setChunks] = useState([]);
  
  useEffect(() => {
    const savedSummary = localStorage.getItem("contextbridge:lastSummary") || "";
    const savedChunks = JSON.parse(localStorage.getItem("contextbridge:lastChunks") || "[]");
    setSummary(savedSummary);
    setChunks(savedChunks);
  }, []);

  // Custom Settings State
  const [includeSummary, setIncludeSummary] = useState(true);
  const [includeSources, setIncludeSources] = useState(false);
  const [includeMetadata, setIncludeMetadata] = useState(true);

  // Construct the final shared content based on settings
  const shareContent = useMemo(() => {
    const parts = [];

    // 1. Header Metadata
    if (includeMetadata) {
      parts.push(`# SmartLINK Report`);
      parts.push(`Date: ${new Date().toLocaleDateString()}`);
      parts.push(`Generated by: ContextBridge AI`);
      parts.push(`---\n`);
    }

    // 2. Summary Section
    if (includeSummary && summary) {
      parts.push(`## Executive Summary\n`);
      parts.push(summary);
      parts.push(`\n`);
    }

    // 3. Source Documents / Chunks
    if (includeSources && chunks.length > 0) {
      parts.push(`## Source References\n`);
      chunks.forEach((chunk, index) => {
        parts.push(`### Source ${index + 1}: ${chunk.filename} (${chunk.domain})`);
        parts.push(`> ${chunk.text.replace(/\n/g, '\n> ')}`);
        parts.push(`\n`);
      });
    }

    if (parts.length === 0) return "Select at least one option to generate content.";

    return parts.join("\n");
  }, [summary, chunks, includeSummary, includeSources, includeMetadata]);

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareContent);
      pushToast("success", "Report copied to clipboard");
    } catch {
      pushToast("error", "Clipboard copy failed");
    }
  };

  const onPrint = () => {
    window.print();
  };

  const onEmail = () => {
    const subject = encodeURIComponent("SmartLINK Report");
    const body = encodeURIComponent(shareContent);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  if (!summary && chunks.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center p-10 text-slate-400">
        <FileText size={48} className="mb-4 opacity-50" />
        <p>No generated content found to share.</p>
        <p className="text-sm">Generate a report in the Transitions tab first.</p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl space-y-8 pb-20 print:pb-0">
      <header className="border-b border-borderline pb-6 print:hidden">
        <h1 className="font-mono text-3xl font-bold tracking-tight">Share Details</h1>
        <p className="mt-2 text-slate-400">
          Customize and export your intelligence report with privacy-first controls.
        </p>
      </header>

      <div className="grid gap-8 lg:grid-cols-3 print:block">
        {/* Left Column: Settings */}
        <div className="space-y-6 lg:col-span-1 print:hidden">
          <div className="rounded-xl border border-borderline bg-surface p-5 shadow-sm">
            <div className="mb-4 flex items-center gap-2 text-slate-200">
              <Settings size={18} />
              <h2 className="font-semibold">Export Settings</h2>
            </div>
            
            <div className="space-y-4">
              <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-transparent p-2 hover:bg-white/5">
                <input
                  type="checkbox"
                  checked={includeSummary}
                  onChange={(e) => setIncludeSummary(e.target.checked)}
                  className="mt-1 h-4 w-4 rounded border-slate-600 bg-slate-800 text-cyan focus:ring-cyan"
                />
                <div>
                  <span className="block text-sm font-medium text-slate-200">Include Summary</span>
                  <span className="text-xs text-slate-500">The AI-generated overview.</span>
                </div>
              </label>

              <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-transparent p-2 hover:bg-white/5">
                <input
                  type="checkbox"
                  checked={includeSources}
                  onChange={(e) => setIncludeSources(e.target.checked)}
                  className="mt-1 h-4 w-4 rounded border-slate-600 bg-slate-800 text-cyan focus:ring-cyan"
                />
                <div>
                  <span className="block text-sm font-medium text-slate-200">Include Source Text</span>
                  <span className="text-xs text-slate-500">
                    Full text excerpts used for generation. {chunks.length > 0 && `(${chunks.length} chunks)`}
                  </span>
                </div>
              </label>

              <label className="flex cursor-pointer items-start gap-3 rounded-lg border border-transparent p-2 hover:bg-white/5">
                <input
                  type="checkbox"
                  checked={includeMetadata}
                  onChange={(e) => setIncludeMetadata(e.target.checked)}
                  className="mt-1 h-4 w-4 rounded border-slate-600 bg-slate-800 text-cyan focus:ring-cyan"
                />
                <div>
                  <span className="block text-sm font-medium text-slate-200">Include Metadata</span>
                  <span className="text-xs text-slate-500">Date, filenames, and disclaimers.</span>
                </div>
              </label>
            </div>
          </div>

          <div className="space-y-3">
            <button
              onClick={onCopy}
              className="flex w-full items-center justify-center gap-2 rounded-lg bg-cyan/10 border border-cyan/30 text-cyan px-4 py-3 font-semibold hover:bg-cyan/20 transition-colors"
            >
              <Copy size={18} />
              Copy to Clipboard
            </button>
            
            <button
              onClick={onPrint}
              className="flex w-full items-center justify-center gap-2 rounded-lg border border-violet/30 bg-violet/10 text-violet-300 px-4 py-3 font-medium hover:bg-violet/20 transition-colors"
            >
              <Printer size={18} />
              Download PDF
            </button>

            <button
              onClick={onEmail}
               className="flex w-full items-center justify-center gap-2 rounded-lg border border-borderline bg-surface px-4 py-3 font-medium text-slate-300 hover:bg-white/5 transition-colors"
            >
              <Mail size={18} />
              Email Report
            </button>
          </div>
        </div>

        {/* Right Column: Preview */}
        <section className="lg:col-span-2 print:col-span-3 print:w-full">
          <div className="mb-2 flex items-center justify-between print:hidden">
            <h2 className="text-sm font-medium text-slate-400">Live Preview</h2>
            <span className="text-xs text-slate-500">{shareContent.length} characters</span>
          </div>
          
          <div className="prose prose-invert max-w-none rounded-xl border border-borderline bg-surface p-6 shadow-inner overflow-auto max-h-[600px] text-sm leading-relaxed scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent print:border-0 print:bg-transparent print:p-0 print:max-h-none print:shadow-none print:text-black print:prose-neutral">
             {includeSummary || includeSources || includeMetadata ? (
               <MarkdownText text={shareContent} />
             ) : (
                <div className="flex h-40 flex-col items-center justify-center text-slate-500">
                  <FileText className="mb-2 opacity-50" />
                  <p>Select options to generate preview</p>
                </div>
             )}
          </div>
          
          <p className="mt-4 text-center text-xs text-slate-500 print:mt-10 print:text-black/50">
            SmartLINK ensures your data remains private. This report is generated locally and is not stored on any external server.
          </p>
        </section>
      </div>
    </div>
  );
}
