import { useMemo } from "react";
import { Copy, Download } from "lucide-react";
import { useToast } from "../context/ToastContext";
import MarkdownText from "../components/MarkdownText";

export default function Share() {
  const { pushToast } = useToast();

  const summary = useMemo(() => localStorage.getItem("contextbridge:lastSummary") || "No generated summary yet.", []);

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      pushToast("success", "Summary copied to clipboard");
    } catch {
      pushToast("error", "Clipboard copy failed");
    }
  };

  return (
    <div className="space-y-5">
      <header>
        <h1 className="font-mono text-3xl">Share</h1>
        <p className="text-sm text-slate-400">Export your latest generated summary.</p>
      </header>

      <section className="printable-summary rounded-xl border border-borderline bg-surface p-6">
        <MarkdownText text={summary} />
        <p className="mt-6 border-t border-borderline pt-4 text-center font-mono text-xs text-slate-400">
          Generated by ContextBridge · User Consented · Locally Processed
        </p>
      </section>

      <div className="flex gap-3">
        <button
          type="button"
          onClick={onCopy}
          className="inline-flex items-center gap-2 rounded-md border border-cyan/60 bg-cyan/10 px-4 py-2 font-mono text-xs text-cyan"
        >
          <Copy size={14} />
          Copy Text
        </button>
        <button
          type="button"
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 rounded-md border border-violet/60 bg-violet/10 px-4 py-2 font-mono text-xs text-violet-300"
        >
          <Download size={14} />
          Download as PDF
        </button>
      </div>
    </div>
  );
}
